name: GemsEconomy
main: me.xanium.gemseconomy.GemsEconomy
version: 4.9.2
author: Xanium
description: A multi-currency economy plugin for spigot servers!
website: https://www.spigotmc.org/resources/gemseconomy.19655/
load: STARTUP
api-version: 1.16
loadbefore:
  - ItemFrameShops
softdepend: [Vault]
commands:
  gems:
    description: Shows your balances
    usage: /gems (account)
    aliases: [gbal, gmoney]
  gemtop:
    description: Shows the top balances of the server
    usage: /gemtop (currency) (page)
    aliases: [gmoneytop, gecotop, gtop, gbaltop, gemstop]
  currency:
    description: Manage the currencies.
    usage: /currency
    aliases: [gcurr, gemscurrencies, gcurrency, currencies]
  gemeconomy:
    description: Give, set or take currency.
    usage: /geco <set|take|give> <account> <amount> (currency)
    aliases: [geconomy, gemeco, geco, gemseconomy]
  gempay:
    description: Pays another account
    usage: /gempay <account> <amount> (currency)
    aliases: [gpay, gemspay]
  cheque:
    usage: /cheque
    description: Write or Redeem a cheque.
    aliases: [note, banknote]
  exchange:
    usage: /exchange
    description: Exchange currencies.
    aliases: [gex, gemsexchange, gexchange]